// Allow needless_return in cfg-gated code paths where return is required
// to exit early before the #[cfg(not(feature))] fallback block.
#![allow(clippy::needless_return)]

mod activity;
mod auth_middleware;
pub(crate) mod background;
pub(crate) mod calibration_runner;
pub(crate) mod cmd_dispatch;
pub(crate) mod embed;
mod embedding_migration;
mod handlers;
mod idle_reembed;
pub(crate) mod monitor;
pub(crate) mod reconnect;
mod routes;
mod scanner;
mod service_installer;
pub(crate) mod session;
pub(crate) mod session_runner;
#[cfg(unix)]
mod tty;
#[cfg(unix)]
mod tty_backfill;
mod tty_embedder;
#[cfg(unix)]
mod tty_finalizer;

// Re-export from skill-daemon-state for internal use via `crate::` paths
pub(crate) use skill_daemon_state::auth;
pub(crate) use skill_daemon_state::state;
pub(crate) use skill_daemon_state::text_embedder;
// tracker is accessed via skill_daemon_state::tracker where needed
// Note: util is a local module that re-exports from skill_daemon_state::util
// plus adds daemon-specific functions (spawn_session_for_target)
pub(crate) mod util;

use skill_daemon_state::util::load_or_create_token;
use skill_daemon_state::AppState;

use std::{net::SocketAddr, path::PathBuf};

use axum::{middleware, routing::get, Router};
use tower_http::cors::{Any, CorsLayer};
use tracing::info;

use axum::http::Method;

fn main() -> anyhow::Result<()> {
    // Synchronous subcommand dispatch. The PTY shim must run *before* tokio
    // is initialised — it does its own blocking I/O and signal handling, and
    // tokio's thread pool would interfere.
    let args: Vec<String> = std::env::args().collect();
    #[cfg(unix)]
    if args.get(1).map(String::as_str) == Some("tty") {
        // Back-compat shim: shell rc files generated by older builds invoke
        // `skill-daemon tty`. The PTY proxy now lives in its own binary
        // (`skill-tty`) so blanket process-name kills (Tauri sidecar reload,
        // kill-old-daemon-on-upgrade) no longer terminate active recorded
        // shells. If we can find the sibling binary, exec into it; otherwise
        // fall back to the in-process implementation so the user's terminal
        // does not break during upgrade.
        tty_shim_dispatch(&args[2..]);
    }
    daemon_main()
}

/// Try to exec the sibling `skill-tty` binary, otherwise run the legacy
/// in-process PTY proxy. Either path calls `std::process::exit` and never
/// returns to the caller.
#[cfg(unix)]
fn tty_shim_dispatch(forward_args: &[String]) -> ! {
    use std::ffi::CString;

    if let Some(sibling) = util::resolve_skill_tty_path() {
        let argv0 = match CString::new(sibling.as_os_str().as_encoded_bytes()) {
            Ok(s) => s,
            Err(_) => fall_back(forward_args),
        };
        let mut owned: Vec<CString> = Vec::with_capacity(forward_args.len() + 1);
        owned.push(argv0);
        for a in forward_args {
            match CString::new(a.as_str()) {
                Ok(s) => owned.push(s),
                Err(_) => fall_back(forward_args),
            }
        }
        let mut argv: Vec<*const libc::c_char> = owned.iter().map(|s| s.as_ptr()).collect();
        argv.push(std::ptr::null());
        // execv replaces this process; only returns on failure.
        // SAFETY: `owned[0]` is a valid NUL-terminated CString and `argv` is a
        // NULL-terminated array of pointers to valid CStrings, all kept alive for
        // the duration of this call.
        unsafe { libc::execv(owned[0].as_ptr(), argv.as_ptr()) };
        eprintln!(
            "skill-daemon tty: execv({}) failed: {} — falling back to in-process shim",
            sibling.display(),
            std::io::Error::last_os_error()
        );
    }
    fall_back(forward_args)
}

#[cfg(unix)]
fn fall_back(forward_args: &[String]) -> ! {
    if let Err(e) = tty::run(forward_args) {
        eprintln!("skill-daemon tty: {e:#}");
        std::process::exit(126);
    }
    // tty::run already calls process::exit on success, but be explicit.
    std::process::exit(0);
}

#[tokio::main]
async fn daemon_main() -> anyhow::Result<()> {
    // Handle --uninstall flag: remove the OS service AND clean up every
    // shell hook we ever wrote into the user's rc files. Removing only the
    // service used to leave stale `source ~/.skill/shell-hooks/...` lines in
    // ~/.zshrc etc. which then errored on every new terminal after the
    // binary was gone — exactly the kind of "modified my dotfiles and
    // didn't put them back" the user gets to be angry about.
    if std::env::args().any(|a| a == "--uninstall") {
        let binary_path = std::env::current_exe().unwrap_or_default();
        let installer = service_installer::ServiceInstaller::new(binary_path);
        installer.uninstall()?;
        println!("Service uninstalled successfully.");

        let skill_dir = skill_data_dir();
        let report = routes::settings::uninstall_all_shell_hooks(&skill_dir);
        for (shell, info) in &report {
            if info.is_empty() {
                continue;
            }
            if info.starts_with("error: ") {
                eprintln!("Shell hook cleanup [{shell}]: {info}");
            } else {
                println!("Cleaned shell hook for {shell} (rc: {info})");
            }
        }
        return Ok(());
    }

    // Write PID file for process management.
    // SKILL_DAEMON_CONFIG_ROOT overrides the location for tests / sandboxes
    // (mirror of the same hook in src-tauri/src/daemon_upgrade.rs).
    let pid_dir = if let Ok(p) = std::env::var("SKILL_DAEMON_CONFIG_ROOT") {
        std::path::PathBuf::from(p)
    } else {
        dirs::config_dir()
            .unwrap_or_else(|| std::path::PathBuf::from("."))
            .join("skill")
            .join("daemon")
    };
    let pid_path = pid_dir.join("daemon.pid");
    if let Some(parent) = pid_path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    let _ = std::fs::write(&pid_path, std::process::id().to_string());

    // Graceful shutdown on SIGTERM/SIGINT
    let shutdown = async {
        let _ = tokio::signal::ctrl_c().await;
        info!("received shutdown signal");
    };

    // Parse CLI flags
    let args: Vec<String> = std::env::args().collect();
    let cli_iroh_logs = args.iter().any(|a| a == "--iroh-logs");

    let skill_dir = skill_data_dir();
    let state = AppState::new(load_or_create_token()?, skill_dir.clone());

    // Voice input (ASR): set the model-cache directory before any session starts.
    skill_asr::init_asr_dirs(&skill_dir);
    // Voice output (daemon-side TTS for the voice loop): point KittenTTS at the
    // model cache. The worker lazy-loads on first speak.
    #[cfg(feature = "voice-tts")]
    {
        skill_tts::init_tts_dirs(&skill_dir);
        // Apply the persisted engine selection so the voice loop speaks through the
        // configured backend (kitten/neutts keep the legacy path; qwen3-tts etc.
        // route through the engine abstraction).
        let s = skill_settings::load_settings(&skill_dir);
        skill_tts::set_active_engine(s.tts_engine, s.tts_model, s.tts_voice);
        if s.tts_preload {
            tokio::spawn(async {
                let _ = skill_tts::tts_init_with_callback(|_| {}).await;
            });
        }
    }

    // CLI flag overrides the persisted setting
    if cli_iroh_logs {
        state
            .iroh_logs_enabled
            .store(true, std::sync::atomic::Ordering::Relaxed);
    }

    init_tracing(state.app_log.clone(), state.iroh_logs_enabled.clone());

    // Spawn the remote-access iroh tunnel.  It proxies authenticated iroh
    // peers to this daemon's HTTP port, enabling phone pairing and remote EEG.
    {
        let api_port = handlers::daemon_addr().port();
        skill_iroh::spawn(
            skill_dir.clone(),
            api_port,
            state.iroh_auth.clone(),
            state.iroh_runtime.clone(),
            state.iroh_peer_map.clone(),
            state.iroh_device_tx.clone(),
        );
    }

    // Restore paired devices from paired_devices.json (fast path) or fall back
    // to settings.json (written by older builds / Tauri side).
    {
        let paired_path = skill_dir.join(skill_constants::PAIRED_DEVICES_FILE);
        let paired: Vec<skill_settings::PairedDevice> = if paired_path.exists() {
            skill_data::util::load_json_or_default(&paired_path)
        } else {
            skill_settings::load_settings(&skill_dir).paired
        };
        if let Ok(mut status) = state.status.lock() {
            status.paired_devices = paired
                .into_iter()
                .map(|p| skill_daemon_common::PairedDeviceResponse {
                    id: p.id,
                    name: p.name,
                    last_seen: p.last_seen,
                })
                .collect();
        }
    }

    activity::start_workers(state.clone());

    // One-shot legacy backfill: read every pre-redesign `.log.zst`,
    // create matching `terminal_sessions` rows with stripped text, link
    // orphan commands by time range. Idempotent — reruns are no-ops.
    #[cfg(unix)]
    tty_backfill::spawn(state.clone());
    // Process closed PTY-shim sessions: slice each finished `.log` by command
    // time-range, ANSI-strip, zstd-compress, write to `terminal_outputs`.
    #[cfg(unix)]
    tty_finalizer::spawn(state.clone());
    // Fill in `terminal_outputs.embedding` for finalized rows. Runs every
    // 30 s, batches of 32, int8-quantised vectors.
    tty_embedder::spawn(state.clone());

    // Auto-refresh installed shell hooks so upgrades propagate fixes (e.g. the
    // macOS `script` SIGWINCH fix) without requiring manual reinstallation.
    {
        let hook_dir = skill_dir.join("shell-hooks");
        for (shell, ext) in &[("zsh", "zsh"), ("bash", "bash"), ("fish", "fish")] {
            let hook_file = hook_dir.join(format!("neuroskill.{ext}"));
            if hook_file.exists() {
                let content = routes::settings::generate_shell_hook(shell);
                if std::fs::write(&hook_file, &content).is_ok() {
                    info!(shell, "refreshed shell hook");
                }
            }
        }
    }

    // One-time embedding-scheme migration — runs its cheap invalidations
    // synchronously *before* the screenshot worker spawns so the backfill picks
    // up the cleared rows.
    embedding_migration::run_if_needed(&state);

    // Spawn daemon-authoritative background loops.
    reconnect::spawn_reconnect_loop(state.clone(), state.reconnect.clone());
    monitor::spawn_status_monitor(state.clone());
    background::spawn_all(state.clone());
    idle_reembed::spawn_idle_reembed_loop(state.clone());

    // Probe HF cache for the currently configured model weights so the UI
    // shows the correct state immediately on first load.
    {
        let st = state.exg_model_status.clone();
        let sd = skill_dir.clone();
        std::thread::spawn(move || {
            let config = skill_eeg::eeg_model_config::load_model_config(&sd);
            if let Some((path, backend)) = routes::settings::probe_weights_for_config(&config) {
                if let Ok(mut status) = st.lock() {
                    status.weights_found = true;
                    status.weights_path = Some(path);
                    status.active_model_backend = Some(backend);
                }
            }
        });
    }

    // Load HNSW label indices from disk (background thread).
    {
        let label_idx = state.label_index.clone();
        let sd = skill_dir.clone();
        std::thread::spawn(move || {
            label_idx.load(&sd);
            info!("label HNSW indices loaded");
        });
    }

    let v1 = routes::core::router()
        .merge(routes::labels::router())
        .merge(routes::history::router())
        .merge(routes::settings::router())
        .merge(routes::api::router())
        .merge(routes::analysis::router())
        .merge(routes::search::router())
        .merge(routes::iroh::router())
        .merge(routes::brain::router())
        .merge(routes::activity_status::router())
        .merge(routes::asr::router())
        .merge(routes::models_validate::router())
        .merge(routes::validation::router());

    // Test-mode endpoints — debug builds only
    #[cfg(debug_assertions)]
    let v1 = v1.merge(routes::test_mode::router());

    let v1 = v1.route_layer(middleware::from_fn_with_state(
        state.clone(),
        auth_middleware::auth_middleware,
    ));

    // Root-level command tunnel for CLI HTTP mode (POST / with JSON body)
    let root_cmd = Router::new()
        .route("/", axum::routing::post(handlers::cmd_tunnel_root))
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            auth_middleware::auth_middleware,
        ));

    // ── CORS — allow Tauri webview (and any local tool) to reach the daemon ──
    //
    // WKWebView on macOS treats `fetch()` from the Tauri devUrl / custom
    // protocol as cross-origin when the target is `http://127.0.0.1:<port>`.
    // Without CORS headers the browser strips the `Authorization` header and
    // the request fails the auth middleware.  A permissive CORS layer fixes
    // this: we already authenticate every request via bearer tokens so the
    // origin check adds no security value.
    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods([
            Method::GET,
            Method::POST,
            Method::PUT,
            Method::PATCH,
            Method::DELETE,
            Method::OPTIONS,
        ])
        .allow_headers(Any)
        .expose_headers(Any);

    let shutdown_state = state.clone();
    // Root-level routes that require authentication
    let authed_root = Router::new()
        .route("/service/install", axum::routing::post(handlers::service_install))
        .route("/service/uninstall", axum::routing::post(handlers::service_uninstall))
        .route("/service/status", get(handlers::service_status))
        // Aliases without /v1/ prefix — used by neuroloop's skill-llm.ts
        .route("/llm/status", get(handlers::llm_status_alias))
        .route("/v1/models", get(handlers::openai_models_alias))
        // Screenshot images (auth required — supports ?token= for <img> tags).
        .route("/screenshots/{filename}", get(handlers::serve_screenshot))
        .route(
            "/screenshots/{date}/{filename}",
            get(handlers::serve_screenshot_with_date),
        )
        .route_layer(middleware::from_fn_with_state(
            state.clone(),
            auth_middleware::auth_middleware,
        ));

    let app = Router::new()
        // Public health check endpoints (no auth required)
        .route("/healthz", get(handlers::healthz))
        .route("/readyz", get(handlers::readyz))
        // Public pairing page for browser extensions (code-gated, no bearer auth)
        .route("/pair/browser", get(handlers::pair_browser_page))
        // Public PIN/token redemption (the PIN is the auth — single-use, 2-min expiry)
        .route("/pair/redeem", axum::routing::post(handlers::pair_redeem))
        // Public claim endpoint for deep-link pairing (extension polls after user approval)
        .route("/pair/claim", axum::routing::post(handlers::pair_claim))
        .merge(authed_root)
        .nest("/v1", v1)
        .merge(root_cmd)
        .layer(cors)
        .with_state(state.clone());

    // ── Auto-start the LLM server if previously enabled ───────────────────────
    //
    // When the user starts the LLM server, `config.enabled` is persisted to
    // disk.  On daemon restart we honour that flag and auto-start the server
    // so the experience is seamless.  If no model is available the start is
    // silently skipped.
    #[cfg(feature = "llm")]
    {
        let llm_state = state.clone();
        tokio::spawn(async move {
            let cfg = llm_state.llm_config.lock().map(|g| g.clone()).unwrap_or_default();
            if cfg.enabled {
                info!("LLM server was enabled — auto-starting");
                let _ =
                    crate::routes::settings_llm_runtime::llm_server_start_impl(axum::extract::State(llm_state)).await;
            }
        });
    }

    let addr = handlers::daemon_addr();
    info!(%addr, "skill daemon listening");

    let listener = tokio::net::TcpListener::bind(addr).await?;
    state.ready.store(true, std::sync::atomic::Ordering::Relaxed);
    info!("daemon ready (accepting requests)");
    axum::serve(listener, app.into_make_service_with_connect_info::<SocketAddr>())
        .with_graceful_shutdown(shutdown)
        .await?;

    info!("shutting down...");

    // Broadcast shutdown event so connected clients can react gracefully.
    let _ = shutdown_state.events_tx.send(skill_daemon_common::EventEnvelope {
        r#type: "DaemonShutdown".to_string(),
        ts_unix_ms: std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64,
        correlation_id: None,
        payload: serde_json::json!({}),
    });

    // 1. Stop the LLM server first — ggml-metal holds GPU resources that
    //    assert-fail if freed during process exit (atexit) instead of being
    //    released explicitly.
    #[cfg(feature = "llm")]
    {
        skill_llm::shutdown_cell(&shutdown_state.llm_state_cell);
        info!("LLM server stopped");
    }

    // 2. Drop the active BLE session so btleplug stops firing delegate
    //    callbacks *before* the broadcast channel is dropped.
    if let Ok(mut slot) = shutdown_state.session_handle.lock() {
        drop(slot.take());
    }

    // 3. Cancel any in-flight EXG weights download.
    shutdown_state
        .exg_download_cancel
        .store(true, std::sync::atomic::Ordering::Relaxed);

    // 4. Checkpoint the activity WAL so the database is clean on next start.
    {
        let sd = shutdown_state.skill_dir.lock().map(|g| g.clone()).unwrap_or_default();
        if let Some(store) = skill_data::activity_store::ActivityStore::open(&sd) {
            store.optimize();
        }
    }

    // Clean up PID file
    let _ = std::fs::remove_file(&pid_path);
    info!("daemon shut down cleanly");
    Ok(())
}

fn skill_data_dir() -> PathBuf {
    std::env::var("SKILL_DATA_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| skill_settings::default_skill_dir())
}

fn init_tracing(
    app_log: std::sync::Arc<std::sync::Mutex<(u64, std::collections::VecDeque<String>)>>,
    iroh_logs_enabled: std::sync::Arc<std::sync::atomic::AtomicBool>,
) {
    use std::io::Write;
    use tracing_subscriber::fmt::MakeWriter;

    /// A writer that writes each byte to both stderr and the shared ring buffer.
    /// `tracing_subscriber::fmt` calls `make_writer()` once per log event and
    /// then calls `write` / `flush` on the returned writer.
    #[derive(Clone)]
    struct TeeWriter {
        log: std::sync::Arc<std::sync::Mutex<(u64, std::collections::VecDeque<String>)>>,
        // Accumulate bytes for the current log line so we can store it whole.
        buf: std::sync::Arc<std::sync::Mutex<Vec<u8>>>,
    }

    impl Write for TeeWriter {
        fn write(&mut self, data: &[u8]) -> std::io::Result<usize> {
            // Forward to real stderr.
            std::io::stderr().write_all(data)?;
            // Buffer locally for line assembly.
            if let Ok(mut b) = self.buf.lock() {
                b.extend_from_slice(data);
                // tracing-subscriber calls `write_all` once per event with the
                // complete formatted line (including the trailing '\n') and
                // never calls `flush()`.  Commit to the ring buffer as soon as
                // we see a newline so log lines are never lost.
                if data.contains(&b'\n') {
                    let line = String::from_utf8_lossy(&b).trim_end_matches('\n').to_string();
                    b.clear();
                    if !line.is_empty() {
                        if let Ok(mut guard) = self.log.lock() {
                            const CAP: usize = 512;
                            let (seq, buf) = &mut *guard;
                            if buf.len() >= CAP {
                                buf.pop_front();
                            }
                            buf.push_back(format!("{}\t{}", seq, line));
                            *seq += 1;
                        }
                    }
                }
            }
            Ok(data.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            std::io::stderr().flush()?;
            // Flush any partial line that didn't end with '\n'.
            let line = if let Ok(mut b) = self.buf.lock() {
                let s = String::from_utf8_lossy(&b).trim_end_matches('\n').to_string();
                b.clear();
                s
            } else {
                return Ok(());
            };
            if line.is_empty() {
                return Ok(());
            }
            if let Ok(mut guard) = self.log.lock() {
                const CAP: usize = 512;
                let (seq, buf) = &mut *guard;
                if buf.len() >= CAP {
                    buf.pop_front();
                }
                buf.push_back(format!("{}\t{}", seq, line));
                *seq += 1;
            }
            Ok(())
        }
    }

    impl<'a> MakeWriter<'a> for TeeWriter {
        type Writer = TeeWriter;
        fn make_writer(&'a self) -> TeeWriter {
            TeeWriter {
                log: self.log.clone(),
                buf: std::sync::Arc::new(std::sync::Mutex::new(Vec::new())),
            }
        }
    }

    let writer = TeeWriter {
        log: app_log,
        buf: std::sync::Arc::new(std::sync::Mutex::new(Vec::new())),
    };

    use tracing_subscriber::layer::SubscriberExt;
    use tracing_subscriber::util::SubscriberInitExt;
    use tracing_subscriber::Layer;

    // Targets that belong to the iroh networking stack.
    const IROH_PREFIXES: &[&str] = &[
        "iroh",
        "quinn",
        "endpoint",
        "magicsock",
        "derp",
        "relay",
        "netcheck",
        "portmapper",
        "discovery",
    ];

    let env_filter =
        tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "skill_daemon=info,info".into());

    let fmt_layer = tracing_subscriber::fmt::layer()
        .with_writer(writer)
        .with_target(false)
        .compact();

    let iroh_flag = iroh_logs_enabled;
    let iroh_filter = tracing_subscriber::filter::filter_fn(move |metadata| {
        // If iroh logs are enabled, allow everything through.
        if iroh_flag.load(std::sync::atomic::Ordering::Relaxed) {
            return true;
        }
        // Suppress iroh-related targets at WARN and below (i.e. WARN, INFO, DEBUG, TRACE).
        // ERROR level always passes through.
        if metadata.level() > &tracing::Level::ERROR {
            let target = metadata.target();
            for prefix in IROH_PREFIXES {
                if target.starts_with(prefix) {
                    return false;
                }
            }
        }
        true
    });

    tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt_layer.with_filter(iroh_filter))
        .init();
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::{to_bytes, Body};
    use axum::http::{header, Request, StatusCode};
    use axum::routing::get;
    use futures::{SinkExt, StreamExt};
    use tempfile::TempDir;
    use tokio_tungstenite::connect_async;
    use tower::ServiceExt;

    fn test_app(state: AppState) -> Router {
        let v1 = Router::new()
            .route("/version", get(handlers::version))
            .route("/events", get(handlers::ws_events))
            .route_layer(middleware::from_fn_with_state(
                state.clone(),
                auth_middleware::auth_middleware,
            ));

        Router::new()
            .route("/healthz", get(handlers::healthz))
            .nest("/v1", v1)
            .with_state(state)
    }

    async fn spawn_test_server(
        app: Router,
    ) -> (
        SocketAddr,
        tokio::sync::oneshot::Sender<()>,
        tokio::task::JoinHandle<()>,
    ) {
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let (tx, rx) = tokio::sync::oneshot::channel::<()>();
        let handle = tokio::spawn(async move {
            let _ = axum::serve(listener, app.into_make_service_with_connect_info::<SocketAddr>())
                .with_graceful_shutdown(async {
                    let _ = rx.await;
                })
                .await;
        });
        (addr, tx, handle)
    }

    fn wait_for_client_count(state: &AppState, want: usize) -> bool {
        for _ in 0..200 {
            let got = state.tracker.lock().map(|g| g.clients.len()).unwrap_or(0);
            if got == want {
                return true;
            }
            std::thread::sleep(std::time::Duration::from_millis(10));
        }
        false
    }

    #[tokio::test]
    async fn router_e2e_healthz_public_and_version_protected() {
        let td = TempDir::new().unwrap();
        let state = AppState::new("test-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());

        let res = app
            .clone()
            .oneshot(Request::builder().uri("/healthz").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(res.status(), StatusCode::OK);

        let res = app
            .clone()
            .oneshot(Request::builder().uri("/v1/version").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(res.status(), StatusCode::UNAUTHORIZED);

        let mut req = Request::builder().uri("/v1/version").body(Body::empty()).unwrap();
        req.headers_mut()
            .insert(header::AUTHORIZATION, "Bearer test-token".parse().unwrap());
        let res = app.clone().oneshot(req).await.unwrap();
        assert_eq!(res.status(), StatusCode::OK);
    }

    #[tokio::test]
    async fn router_e2e_forbidden_acl_and_ws_auth_gate() {
        let td = TempDir::new().unwrap();
        let state = AppState::new("default-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());

        let stream_secret = {
            let mut store = state.token_store.lock().unwrap();
            let tok = store
                .create(
                    "stream".to_string(),
                    crate::auth::TokenAcl::Stream,
                    crate::auth::TokenExpiry::Never,
                )
                .expect("create stream token");
            tok.token
        };

        // ACL denial on non-read method.
        let mut req = Request::builder()
            .method("POST")
            .uri("/v1/version")
            .body(Body::empty())
            .unwrap();
        req.headers_mut().insert(
            header::AUTHORIZATION,
            format!("Bearer {stream_secret}").parse().unwrap(),
        );
        let res = app.clone().oneshot(req).await.unwrap();
        assert_eq!(res.status(), StatusCode::FORBIDDEN);

        // WS endpoint with missing token should be unauthorized.
        let res = app
            .clone()
            .oneshot(Request::builder().uri("/v1/events").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(res.status(), StatusCode::UNAUTHORIZED);

        // WS endpoint with valid token passes auth layer; without upgrade headers
        // handler will return 400 (expected in this in-process HTTP test).
        let mut req = Request::builder()
            .uri("/v1/events?token=default-token")
            .body(Body::empty())
            .unwrap();
        req.headers_mut().insert(header::CONNECTION, "upgrade".parse().unwrap());
        req.headers_mut().insert(header::UPGRADE, "websocket".parse().unwrap());
        req.headers_mut().insert("sec-websocket-version", "13".parse().unwrap());
        req.headers_mut()
            .insert("sec-websocket-key", "dGVzdA==".parse().unwrap());
        let res = app.clone().oneshot(req).await.unwrap();
        assert_ne!(res.status(), StatusCode::UNAUTHORIZED);

        // Unauthorized body shape contract.
        let res = app
            .clone()
            .oneshot(Request::builder().uri("/v1/version").body(Body::empty()).unwrap())
            .await
            .unwrap();
        let status = res.status();
        let body = to_bytes(res.into_body(), usize::MAX).await.unwrap();
        let v: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(status, StatusCode::UNAUTHORIZED);
        assert_eq!(v["code"], "unauthorized");
    }

    #[tokio::test]
    async fn router_e2e_forbidden_body_shape() {
        let td = TempDir::new().unwrap();
        let state = AppState::new("default-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());

        let stream_secret = {
            let mut store = state.token_store.lock().unwrap();
            let tok = store
                .create(
                    "stream".to_string(),
                    crate::auth::TokenAcl::Stream,
                    crate::auth::TokenExpiry::Never,
                )
                .expect("create stream token");
            tok.token
        };

        let mut req = Request::builder()
            .method("POST")
            .uri("/v1/version")
            .body(Body::empty())
            .unwrap();
        req.headers_mut().insert(
            header::AUTHORIZATION,
            format!("Bearer {stream_secret}").parse().unwrap(),
        );

        let res = app.clone().oneshot(req).await.unwrap();
        let status = res.status();
        let body = to_bytes(res.into_body(), usize::MAX).await.unwrap();
        let v: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(status, StatusCode::FORBIDDEN);
        assert_eq!(v["code"], "forbidden");
    }

    #[tokio::test]
    async fn ws_receives_broadcast_and_tracks_clients() {
        let td = TempDir::new().unwrap();
        let state = AppState::new("ws-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());
        let (addr, shutdown_tx, handle) = spawn_test_server(app).await;

        let url = format!("ws://{addr}/v1/events?token=ws-token");
        let (mut ws, _resp) = connect_async(url).await.expect("ws connect");
        assert!(
            wait_for_client_count(&state, 1),
            "client should be tracked after ws connect"
        );

        let _ = state.events_tx.send(skill_daemon_common::EventEnvelope {
            r#type: "Ping".to_string(),
            ts_unix_ms: 1,
            correlation_id: None,
            payload: serde_json::json!({"ok": true}),
        });

        let mut saw_ping = false;
        for _ in 0..8 {
            let msg = tokio::time::timeout(std::time::Duration::from_secs(2), ws.next())
                .await
                .expect("ws receive timeout")
                .expect("ws closed")
                .expect("ws error");
            if let tokio_tungstenite::tungstenite::Message::Text(txt) = msg {
                let v: serde_json::Value = serde_json::from_str(&txt).unwrap();
                if v["type"] == "Ping" {
                    assert_eq!(v["payload"]["ok"], true);
                    saw_ping = true;
                    break;
                }
            }
        }
        assert!(saw_ping, "did not observe Ping event on websocket stream");

        let _ = ws.close(None).await;

        let _ = shutdown_tx.send(());
        let _ = handle.await;
    }

    #[tokio::test]
    async fn ws_non_text_frame_does_not_break_stream() {
        let td = TempDir::new().unwrap();
        let state = AppState::new("ws-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());
        let (addr, shutdown_tx, handle) = spawn_test_server(app).await;

        let url = format!("ws://{addr}/v1/events?token=ws-token");
        let (mut ws, _resp) = connect_async(url).await.expect("ws connect");

        // Send a binary frame; server should ignore unsupported frame types,
        // not drop the socket.
        let _ = ws
            .send(tokio_tungstenite::tungstenite::Message::Binary(vec![0, 1, 2].into()))
            .await;

        let _ = state.events_tx.send(skill_daemon_common::EventEnvelope {
            r#type: "AfterBinary".to_string(),
            ts_unix_ms: 2,
            correlation_id: None,
            payload: serde_json::json!({"ok": true}),
        });

        let mut saw = false;
        for _ in 0..8 {
            let msg = tokio::time::timeout(std::time::Duration::from_secs(2), ws.next())
                .await
                .expect("ws receive timeout")
                .expect("ws closed")
                .expect("ws error");
            if let tokio_tungstenite::tungstenite::Message::Text(txt) = msg {
                let v: serde_json::Value = serde_json::from_str(&txt).unwrap();
                if v["type"] == "AfterBinary" {
                    saw = true;
                    break;
                }
            }
        }
        assert!(saw, "stream should continue after non-text frame");

        let _ = ws.close(None).await;
        let _ = shutdown_tx.send(());
        let _ = handle.await;
    }

    /// Regression: command dispatch must stay responsive while broadcast
    /// events are flooding the connection.
    ///
    /// Before the priority-queue + subscribe-gating fix, ~300–500 high-rate
    /// events/sec on a single WS connection would fill the kernel TCP send
    /// buffer, block `sender.send(event).await`, and starve every command
    /// response — the smoke test saw 15s per-command timeouts.
    ///
    /// This test subscribes to the high-rate stream, broadcasts 1000
    /// EegSample envelopes, and asserts the response to `{command:"status"}`
    /// arrives within 1500ms. The pre-fix daemon would take 5+s.
    #[tokio::test]
    async fn ws_command_responds_under_event_flood() {
        use tokio_tungstenite::tungstenite::Message;

        let td = TempDir::new().unwrap();
        let state = AppState::new("flood-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());
        let (addr, shutdown_tx, handle) = spawn_test_server(app).await;

        let url = format!("ws://{addr}/v1/events?token=flood-token");
        let (mut ws, _resp) = connect_async(url).await.expect("ws connect");

        // 1) drain welcome envelope
        let _ = tokio::time::timeout(std::time::Duration::from_secs(2), ws.next())
            .await
            .expect("welcome timeout")
            .expect("ws closed")
            .expect("ws error");

        // 2) opt in to the high-rate stream
        ws.send(Message::Text(r#"{"command":"subscribe","events":["*"]}"#.into()))
            .await
            .expect("send subscribe");

        // 3) drain the subscribe ack
        for _ in 0..4 {
            let msg = tokio::time::timeout(std::time::Duration::from_secs(2), ws.next())
                .await
                .expect("ack timeout")
                .expect("ws closed")
                .expect("ws error");
            if let Message::Text(t) = msg {
                let v: serde_json::Value = serde_json::from_str(&t).unwrap();
                if v["command"] == "subscribe" {
                    break;
                }
            }
        }

        // 4) flood the broadcast channel with high-rate envelopes
        for i in 0..1000 {
            let _ = state.events_tx.send(skill_daemon_common::EventEnvelope {
                r#type: "EegSample".to_string(),
                ts_unix_ms: i as u64,
                correlation_id: None,
                payload: serde_json::json!({"channels": [0.0, 0.0, 0.0, 0.0], "timestamp": i as f64}),
            });
        }

        // 5) send a command and time its response
        let t0 = std::time::Instant::now();
        ws.send(Message::Text(r#"{"command":"status"}"#.into()))
            .await
            .expect("send status");

        let mut saw_status = false;
        let mut elapsed = std::time::Duration::ZERO;
        // Drain up to ~2000 frames waiting for the response — most will
        // be EegSample echoes that the sender task hasn't drained yet.
        for _ in 0..2500 {
            let msg = tokio::time::timeout(std::time::Duration::from_secs(3), ws.next())
                .await
                .expect("response timeout")
                .expect("ws closed")
                .expect("ws error");
            if let Message::Text(t) = msg {
                let v: serde_json::Value = serde_json::from_str(&t).unwrap();
                if v["command"] == "status" {
                    saw_status = true;
                    elapsed = t0.elapsed();
                    break;
                }
            }
        }
        assert!(saw_status, "status response never arrived under event flood");
        assert!(
            elapsed < std::time::Duration::from_millis(1500),
            "status response took {elapsed:?} under event flood — \
             priority-queue regression (pre-fix took 5+s)"
        );

        let _ = ws.close(None).await;
        let _ = shutdown_tx.send(());
        let _ = handle.await;
    }

    /// Regression: high-rate events MUST be filtered out when the client
    /// hasn't subscribed. Otherwise dashboards that don't opt in still get
    /// the firehose and the daemon's TCP send buffer fills.
    #[tokio::test]
    async fn ws_filters_high_rate_events_by_default() {
        use tokio_tungstenite::tungstenite::Message;

        let td = TempDir::new().unwrap();
        let state = AppState::new("filter-token".to_string(), td.path().to_path_buf());
        let app = test_app(state.clone());
        let (addr, shutdown_tx, handle) = spawn_test_server(app).await;

        let url = format!("ws://{addr}/v1/events?token=filter-token");
        let (mut ws, _resp) = connect_async(url).await.expect("ws connect");

        // welcome
        let _ = tokio::time::timeout(std::time::Duration::from_secs(2), ws.next())
            .await
            .expect("welcome timeout")
            .expect("ws closed")
            .expect("ws error");

        // Fire one high-rate and one low-rate event.
        let _ = state.events_tx.send(skill_daemon_common::EventEnvelope {
            r#type: "EegSample".to_string(),
            ts_unix_ms: 1,
            correlation_id: None,
            payload: serde_json::json!({"x": 1}),
        });
        let _ = state.events_tx.send(skill_daemon_common::EventEnvelope {
            r#type: "StatusUpdate".to_string(),
            ts_unix_ms: 2,
            correlation_id: None,
            payload: serde_json::json!({"x": 2}),
        });

        let mut saw_eeg = false;
        let mut saw_status = false;
        for _ in 0..8 {
            let res = tokio::time::timeout(std::time::Duration::from_millis(500), ws.next()).await;
            let Ok(Some(Ok(Message::Text(t)))) = res else {
                break;
            };
            let v: serde_json::Value = serde_json::from_str(&t).unwrap();
            match v["type"].as_str() {
                Some("EegSample") => saw_eeg = true,
                Some("StatusUpdate") => saw_status = true,
                _ => {}
            }
        }
        assert!(saw_status, "low-rate event must be forwarded");
        assert!(!saw_eeg, "high-rate event must be filtered until client subscribes");

        let _ = ws.close(None).await;
        let _ = shutdown_tx.send(());
        let _ = handle.await;
    }
}
